### ISSUE TITLE
ArchiveAdmin requires CMS JS/CSS

### ISSUE THREAD

**Issue by mlewis-everley** [silverstripe/silverstripe-versioned-admin#102]
As in the title, `ArchiveAdmin` requires CMS dependencies, but doesn't seem to need them (I commented them out and it still seems to work fine).

The code is located at: https://github.com/silverstripe/silverstripe-versioned-admin/blob/master/src/ArchiveAdmin.php#L53

If the css/js are needed, is it worth adding those requirements inside a check to see if the CSM module is installed?

I can probably add this as a PR if that helps?

**Comment by ScopeyNZ** [comment]
🤔 

Please, open a PR and we can debate it there. #29 introduced this and it's a React app so all of its requirements should be within its own bundle.

**Comment by robbieaverill** [comment]
@mlewis-everley still keen to submit a PR?

**Comment by mlewis-everley** [comment]
I can do, I will leave this tab open so I remember to do it!

**Comment by mlewis-everley** [comment]
@robbieaverill PR made

**Comment by robbieaverill** [comment]
Merged, thanks

**Comment by mlewis-everley** [comment]
Cheers @robbieaverill , do you need me to create a PR for 1.2 branch, or is that in hand?

**Comment by robbieaverill** [comment]
Nope, it'll get merged up eventually =)
