### ISSUE TITLE
Replace our Diff implementation (and remove thirdparty/difflib.php)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-versioned-admin#103]
## Overview

One of the last bastions of the SilverStripe 2.x universe: The crazy way we do HTML diffing, through [Diff.php](https://github.com/silverstripe/silverstripe-framework/blob/4/src/View/Parsers/Diff.php), which uses a PHP library that's old enough to drink: [difflib.php](https://github.com/silverstripe/silverstripe-framework/blob/4/thirdparty/difflib/difflib.php). And a grand total of [two glorious unit tests](https://github.com/silverstripe/silverstripe-framework/blob/4/tests/php/View/Parsers/DiffTest.php).

This got triggered by looking through workflow, and reviewing a change request. Something as simple as an added paragraph didn't show up as a highlighted change there (it gets confused where to put the `<ins>` tags). And I really don't feel like debugging this in 17 year old code.

![image](https://user-images.githubusercontent.com/111025/54164775-cc184e80-44c2-11e9-9c6b-07d5e1661f3c.png)

## Option 1: PHP library

Would require us to provide API responses with the raw HTML diff to be rendered in field contents. Somewhat conflicts with our React direction (and React powered form fields). But allows us to render diffs in emails (e.g. workflow notifications).

 * [gathercontent/htmldiff](https://github.com/gathercontent/htmldiff): My current favourite, but also quote old (written five years ago for PHP 5.3). Requires tidy, not sure if that would change core requirements.
 * [chrisboulton/php-diff](https://github.com/chrisboulton/php-diff): BSD licensed. Mostly written 9 years ago, but has PHP 7 compat. Virtually no unit tests
 * [caxy/php-htmldiff](https://packagist.org/packages/caxy/php-htmldiff): Very popular and active, but licensed under GPLv2, so a non-starter
 * [iCAPLyon1/HTMLDiff](https://github.com/iCAPLyon1/HtmlDiff): Requires Silex, kind of a non-starter. Likely not PHP7 compat, but we could fix that. No tests.

## Option 2: JS library

This would be more in line with our general Reactification of the CMS. We'd pass two versions of a record through the API, and the client does the work. Depending on the form field, we could have our own custom diff implementations (e.g. a dropdownfield showing each item in the dropdown with individual red/green backgrounds).

 * [markedjs/html-differ](https://www.npmjs.com/package/@markedjs/html-differ): MIT license, fairly comprehensive and well tested. Returns "diff objects", which we need to reassemble back to HTML. `getDiffText()` might do that?
 * [diff2html](https://github.com/rtfpessoa/diff2html): Only does json and diff strings (github style)
 * [prettydiff](https://github.com/prettydiff/prettydiff): Looks pretty oldschool, but has an XML lexer mode. 

## Notes

 * See [Diff doesn't show an entirely new line as an addition](https://github.com/silverstripe/silverstripe-versioned-admin/issues/82)
 * See [Diff view in Workflow Actions tab can break for shortcodes](https://github.com/symbiote/silverstripe-advancedworkflow/issues/384)
 * See [Indication of new additions/changes not visible enough](https://github.com/silverstripe/silverstripe-versioned-admin/issues/97)
 * See [Workflow: View diff to emails and in admin UI](https://github.com/symbiote/silverstripe-advancedworkflow/issues/173)

**Comment by robbieaverill** [comment]
Here's some relevant convo around using libraries for this when we developed history viewer: https://github.com/silverstripe/silverstripe-versioned/issues/96#issuecomment-383789990

**Comment by pjayme** [comment]
Hiya, I've noticed this in lists too on `SS4.2.4`:

In this case I have added a 5th item to this list:
```
<ul>
 <li>1</li>
 <li>2</li>
 <li>3</li>
 <li>4</li>
 <li class="c1"><ins>
 <li>5</li>
 </ins></li>
</ul>
```

**Comment by GuySartorelli** [comment]
Option 1 was done in CMS 5
