### ISSUE TITLE
Date format not updating with User Settings Interface Language

### ISSUE THREAD

**Issue by gavin-murphy** [silverstripe/silverstripe-versioned-admin#117]
WIth latest SilverStripe 4.x the Site Settings no longer have user-specified date formats. Instead, there is a higher level 'Interface Language'.
Our users are expecting that new field to drive date formats elsewhere in the CMS, including the versioned admin views.
E.g. a user with English (US) might expect a MM/DD/YYYY format, whilst an English (UK) user might expect DD/MM/YYYY, say.
The versioned admin module doesn't change date formats in accordance with this user setting.

**Comment by chillu** [comment]
Note that the explicit date/time preferences were removed on purpose from member settings, see https://github.com/silverstripe/silverstripe-framework/issues/6626

>  Remove date/time format customisation in admin/myprofile: It no longer applies for a large amount of use cases (date fields for 85% of users on HTML5 browsers). It means readonly dates (e.g. page history view) will use the default for your locale, but that's acceptable. Admins could still override the locale format globally for all users through YAML config.

This is mentioned in the changelog: https://docs.silverstripe.org/en/4/changelogs/4.0.0/#member-date-time-fields

Every locale selected as an "interface language" should have a default format though, and we should make it easy to apply this.

Gavin, I'm assuming you're talking about this here?
![image](https://user-images.githubusercontent.com/111025/59806500-98ae5100-9348-11e9-935e-5b94168a908f.png)

**Comment by gavin-murphy** [comment]
Thanks, Ingo.

Correct.

The global config in YAML is one things, but having users from other
countries with a level of expectation leads to a level of uncertainty when
viewing dates in the CMS. One of clients, for example, have authors /
contributors all over the world, so a global setting is less ideal.

Associating a default format with the new language / locale would be useful.

Cheers.

<deviate>
making things different

developing web sites and web applications for devices big and small

gavin murphy
director

deviate.net.nz
04 381 6842
0210 774 221

Level 4
58 Victoria Street
Wellington 6011

PO Box 11169
2 Manners Street
Wellington 6011

*Important:  If you have received this message in error please notify the
sender immediately and then delete this message along with any attachments.
Please treat the content of this message as private and confidential.*

**Comment by brynwhyman** [comment]
I don't want to confuse things here but I'm running version `silverstripe/versioned-admin 1.2.x-dev`(with cwp/cwp 2.3.x-dev, `silverstripe/framework 4.4.x-dev`) and changing the Interface Language at a user profile level updates the date format in the page history viewer (and other places) to the new date formate that I'm expecting.

With the Interface Language changed to 'English (United Kingdom)' I see:

![image](https://user-images.githubusercontent.com/15868440/59808094-d57d4680-934e-11e9-8b5c-4b643ca2e59c.png)

If I change the Interface Language back to 'US' I see US date/time formats. I can't see anything implemented in `cwp/cwp` that's introducing this on top of core, but I'm not a developer :P

**Comment by brynwhyman** [comment]
That's also what I'd expect, based on the docs: https://docs.silverstripe.org/en/4/developer_guides/i18n/#date-and-time-formats

**Comment by gavin-murphy** [comment]
Perhaps it has been addressed somewhere in the framework / supporting CWP
modules as my profile is set to United Kingdom but I still see US formats
in History

[image: Annotation 2019-06-20 115833.jpg]

The client is on CWP 2.2.3 so they are framework 4.3.3.

The next recipe upgrade might fix this.

Would be good if it also fixes it in Queued Jobs module, as our client has
raised that one, too.

<deviate>
making things different

developing web sites and web applications for devices big and small

gavin murphy
director

deviate.net.nz
04 381 6842
0210 774 221

Level 4
58 Victoria Street
Wellington 6011

PO Box 11169
2 Manners Street
Wellington 6011

*Important:  If you have received this message in error please notify the
sender immediately and then delete this message along with any attachments.
Please treat the content of this message as private and confidential.*

**Comment by chillu** [comment]
Ooooh, we've fixed this in 4.4, it's broken in 4.3.

4.3

![image](https://user-images.githubusercontent.com/111025/59809548-18dab380-9355-11e9-950a-4d40977e18d0.png)

4.4

![image](https://user-images.githubusercontent.com/111025/59809558-21cb8500-9355-11e9-89fa-588770a39985.png)

**Comment by gavin-murphy** [comment]
Nice. Thanks for confirming.

Cheers

<deviate>
making things different

developing web sites and web applications for devices big and small

gavin murphy
director

deviate.net.nz
04 381 6842
0210 774 221

Level 4
58 Victoria Street
Wellington 6011

PO Box 11169
2 Manners Street
Wellington 6011

*Important:  If you have received this message in error please notify the
sender immediately and then delete this message along with any attachments.
Please treat the content of this message as private and confidential.*

**Comment by brynwhyman** [comment]
Nice!*
