### ISSUE TITLE
Align minor version number with rest of core in CMS 4.6

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-versioned-admin#148]
Currently, there's a disconnect in version between other core modules (currently sitting at 1.5.x / 4.5.x) and this module (currently sitting at 1.3.x). This is due to versioned-admin being released a few minor versions into the CMS 4 series. It's a point of confusion any time we touch this module, and there's no real reason to keep it this way.

In order to resolve this confusion, we should make the next minor release of versioned-admin `1.6.0`, to be released alongside recipe-cms `4.6.0` in the next few months. We may also document this discrepancy in the README.

**Comment by Cheddam** [comment]
The module is aligned as of `1.6.0-beta1` / `4.6.0-beta1`.

**Comment by robbieaverill** [comment]
I think you're chasing a tail by doing this to be honest. Where do you stop? Mime validator (now part of core), login forms, config module?

**Comment by Cheddam** [comment]
Totally take your point, and I won't be pursuing alignment for any other modules - this case was just particularly egregious to me, since the rest of the x-admin modules are in sync.
