### ISSUE TITLE
A user without Edit permission is still offered the Revert to this version button

### ISSUE THREAD

**Issue by mikenz** [silverstripe/silverstripe-versioned-admin#154]
When logged in as a user with permission to view any page but not edit a page:
![image](https://user-images.githubusercontent.com/6816/81117797-d83f5500-8f7b-11ea-9958-b6d83eb156a7.png)

The user is offered an active "Revert to this version" button. 
![image](https://user-images.githubusercontent.com/6816/81117925-0ae94d80-8f7c-11ea-8a7f-6a15dfd02233.png)

When clicked this fails, but the button is left in a loading state and the error message is never displayed.
![image](https://user-images.githubusercontent.com/6816/81117880-f86f1400-8f7b-11ea-8f0d-4b1ea4bb1c07.png)

Expected behaviour:
The Revert to this version button is disabled with an appropriate title. As seen when viewing the current version:
![image](https://user-images.githubusercontent.com/6816/81118033-3f5d0980-8f7c-11ea-9703-72dcd4e5c6f1.png)

## PR
- [x] https://github.com/silverstripe/silverstripe-versioned-admin/pull/181

**Comment by emteknetnz** [comment]
Fixed in https://github.com/silverstripe/silverstripe-versioned-admin/pull/181/files
