### ISSUE TITLE
Model admin name should be 'Archive' not 'Archives'

### ISSUE THREAD

**Issue by sachajudd** [silverstripe/silverstripe-versioned-admin#156]
I think this was a mistake but it should technically be 'Archive' not 'Archives'.

[User help on how we talk about the Archive](https://userhelp.silverstripe.org/en/4/creating_pages_and_content/archive/#archive)

Relates to https://github.com/silverstripe/silverstripe-cms/issues/1575

**Comment by robbieaverill** [comment]
Technically this would be an enhancement - original designs here :) https://projects.invisionapp.com/share/FTG16IYV5KB#/screens/280476971

**Comment by sachajudd** [comment]
Yeah this was a design mishap where it was updated in one place and not another causing inconsistent across the board when it was developed.
