### ISSUE TITLE
Restore batch action seems non-sensical

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-versioned-admin#159]
1.x-dev 0a18845

I was logged in as a "Content Author"

Select `Restore` from the Batch Actions drop down

You don't see archived pages, so not possible to restore anything

Seems like the option should be removed

**Comment by brynwhyman** [comment]
Closing for: https://github.com/silverstripe/silverstripe-cms/issues/2426 (which aims to remove the functionality)
