### ISSUE TITLE
"Select a content type" seems to be inoperative.

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-versioned-admin#183]
Context: I'm using versioned-admin in a non-cms project (no pages / sitetree).

In the versioned admin, I see only one tab with "Others" and a gridfield showing an archive of the first selected class.

However, the dropdown to select another model seems to do nothing.

![image](https://user-images.githubusercontent.com/936064/97525433-adeec180-1a0b-11eb-9a48-13e466f5209c.png)

Should I expect the gridfield to refresh with the archive for the selected class?

**Comment by tractorcow** [comment]
Code in question that seems to not work https://github.com/silverstripe/silverstripe-versioned-admin/blob/1d7a0b71edcbea9b4380a8808785f340c40ac1cd/client/src/legacy/ArchiveAdmin/ArchiveAdmin.js

**Comment by tractorcow** [comment]
Could it be due to the fact that chosen is replacing the `select` with a chosen field?

**Comment by tractorcow** [comment]
OH
```---
Name: versionedadmincmsconfig
Only:
  moduleexists: silverstripe/cms
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\CMS\Controllers\CMSPageHistoryController:
    class: SilverStripe\VersionedAdmin\Controllers\CMSPageHistoryViewerController

SilverStripe\CMS\Controllers\CMSMain:
  extensions:
    - SilverStripe\VersionedAdmin\Extensions\CMSMainExtension

SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'silverstripe/versioned-admin:client/dist/js/bundle.js'
  extra_requirements_css:
    - 'silverstripe/versioned-admin:client/dist/styles/bundle.css'

```

I dont' have silverstripe/cms installed. That's why.

**Comment by tractorcow** [comment]
PR at https://github.com/silverstripe/silverstripe-versioned-admin/pull/190

**Comment by emteknetnz** [comment]
Linked PR has been merged
