### ISSUE TITLE
/tests/ should be export-ignore in .gitattributes

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-versioned-admin#199]
`composer install --prefer-dist` is installing tests for this module. We probably should not be packaging them.

# Pull request
- [ ] https://github.com/silverstripe/silverstripe-versioned-admin/pull/200

**Comment by maxime-rainville** [comment]
Looks like it was just a typo in `.gitattributes`

This should take care of it https://github.com/silverstripe/silverstripe-versioned-admin/pull/200
