### ISSUE TITLE
BUG: History Records are not showing the page version state correctly 

### ISSUE THREAD

**Issue by MelissaWu-SS** [silverstripe/silverstripe-versioned-admin#255]
The Records in History tab of a page are not showing the page version state correctly. 

- It shows 'Published' when the page is actually only **saved** but not **published**
- All version records turn to 'Saved' except for the first 'Created' record when the page is 'unpublished'

## Acceptance criteria
- [ ] The messaging on the version history page is consistent.
- [ ] The state of each version is correct.
- [ ] The scenario is covered by a behat test.

https://user-images.githubusercontent.com/81267819/193479344-fdb5e215-95be-49fe-9a5c-4b237db0ecc4.mov

The logic for showing the state seems have bug: https://github.com/silverstripe/silverstripe-versioned-admin/blob/0e407f2c790ec449df04a2a3880136b5d77bcf3a/client/src/components/HistoryViewer/HistoryViewerVersionState.js#L25

## PRs
- https://github.com/silverstripe/silverstripe-versioned/pull/402
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/283

**Comment by maxime-rainville** [comment]
There's a PR for this already: https://github.com/silverstripe/silverstripe-versioned-admin/pull/258

We want to look at some UX feedback before coming up with a final solution. However, if the #258 is an obvious improvements, maybe we just merge it.

**Comment by hirenatfos** [comment]
Any updates on this issue ?

**Comment by GuySartorelli** [comment]
@hirenatfos This issue is in our backlog. In a future backlog refinement meeting we will refine this card, and at some stage after that someone will review the associated pull request.

**Comment by NightJar** [comment]
> There's a PR for this already: #258
> 
> We want to look at some UX feedback before coming up with a final solution. However, if the #258 is an obvious improvements, maybe we just merge it.

Sorry I'm confused as what UX would be needed for. Can you please elaborate @maxime-rainville ?
As I see it, this is a regression. The bugfix will simply restore old (correct) behaviour.

**Comment by NightJar** [comment]
This is a bug with GraphQL 4.
Downgrading to GraphQL 3 resolves the issue.

- `composer create-project silverstripe/installer test`
- dev/build
- browse to `/admin/pages/edit/show/1`
- Edit and save (NOT publish) the home page twice.
- browse to `/admin/pages/history/show/1`
- 👀 Records show (oldest to newest): **Created, Published, Published, Published**. ❌ 
- `composer require silverstripe/graphql ^3`
- dev/build
- browse to `/admin/pages/history/show/1`
- 👀 Records show (oldest to newest): **Created, Published, Saved, Saved** ✔️ 

**In both cases the installed version of `silverstripe/versioned-admin` is `1.12.0`**

**Comment by NightJar** [comment]
#258 only addresses half of this issue, and simply patches a symptom rather than remediate the cause.

The GraphQL query returns bad information with GQL 4 installed. This is not a client processing issue.

The key `published: true` appears for records that should read `published: false`.

I would assume that the inverse is also true for unpublished pages (showing "Saved" for all versions).

![image](https://user-images.githubusercontent.com/778003/228798780-ee852a7c-e010-46b5-a940-cdee1f832261.png)

**Comment by NightJar** [comment]
So, as this module seems to define no query resolver and has no code to control that output, the bug is _probably_ actually with [**Versioned**](https://github.com/silverstripe/silverstripe-versioned/pull/308)

**Comment by GuySartorelli** [comment]
Awesome, thank you for that context! 💙

**Comment by emteknetnz** [comment]
Fixed and tagged as [1.12.1](https://github.com/silverstripe/silverstripe-versioned/releases/tag/1.12.1) in versioned. Cheers for the investigation @NightJar was very helpful
