### ISSUE TITLE
Build a new GridFieldComponent to support Historic views

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-versioned-admin#26]
At current the history viewer is implemented in two ways:

0. As a `FormField` - [`HistoryViewerField`](https://github.com/silverstripe/silverstripe-versioned-admin/blob/926985705a5c3fb4b1e8f33ac030dd9e8bd8b9bf/src/Forms/HistoryViewerField.php)
1. Via a [controller dealing with Page history](https://github.com/silverstripe/silverstripe-versioned-admin/blob/926985705a5c3fb4b1e8f33ac030dd9e8bd8b9bf/src/Controllers/CMSPageHistoryViewerController.php) using [`HistoryViewerField`](https://github.com/silverstripe/silverstripe-versioned-admin/blob/4c982ed527e76a293cebbfc902bcbfc52fd0a887/src/Controllers/CMSPageHistoryViewerController.php#L45)
2. Any other reasonably generic [`Form`](https://github.com/dnadesign/silverstripe-elemental/blob/c5d5b8e2fd55c11724565635f6f75253d1c43004/src/Models/BaseElement.php#L296) that uses the `HistoryViewerField`

Problems with this second method is that it often does not make contextual/semantic sense to have a history field nestled in amongst other edit fields for Form Submission, leading to it usually being separated via a `Tab`, which then comes with it's own set of problems such as exemplified by #22 and to a lesser extent https://github.com/silverstripe/silverstripe-versioned-admin/issues/1#issuecomment-401658520

Ideally there would be a new `RequestHandler` implementing the `GridField_URLHandler` interface, allowing for a new endpoint specifically for dealing with history of versioned objects, in a similar manner to how `GridFieldDetailForm` is for editing the latest version.

**As**
A developer
**I want**
an easy way to add historic views to `Versioned` `DataObjects` in the CMS
**So that**
I can support Content Authors in auditing a change history from objects managed in a `GridField`
**Instead of**
Adding a `HistoryViewerField` to the current version of that object's _edit_ `Form`
**So that**
The component is cleanly separated in concern, reusable, easily maintainable, and provides a consistent user experience throughout different areas of the CMS dealing with History.

**Comment by robbieaverill** [comment]
To clarify, the problem you're trying to fix with this is that different styling is required in different contexts, as well as certain things like React routing being tricky when the HistoryViewerField is added to a form in the CMS?

I'm pretty unclear about how your suggested solution would help with this. Perhaps you could do a lightweight RFC at some point to make it clearer?

**Comment by robbieaverill** [comment]
Feel free to reopen if you'd like to revisit this =)

**Comment by NightJar** [comment]
The UI is react driven now (for elemental as a whole) so separate controllers aren't really a thing now anyway.
