### ISSUE TITLE
Trailing slash expected for other model selector field

### ISSUE THREAD

**Issue by thats4shaw** [silverstripe/silverstripe-versioned-admin#291]
The other model selector field adds a trailing slash to the `data-others-archive-url` attribute however the framework now strips it out by default since [CMS5](https://docs.silverstripe.org/en/5/changelogs/5.0.0/#trailing-slash). 

This causes any selection of this dropdown to return a 404.

If trailing slashes are reenabled everything works again.  Will add a PR when I get a spare moment but wanted to document so I don't forget :-).

## Acceptance criteria
- You can select other models from the drop down in the "Archive" CMS section
- The scenario is covered by a Behat test

## Notes
- We are talking about the drop down on this page `admin/archive?others=1`

## PRs
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/293

**Comment by GuySartorelli** [comment]
PR merged and tagged as [2.0.1](https://github.com/silverstripe/silverstripe-versioned-admin/releases/tag/2.0.1)
