### ISSUE TITLE
History view not visible in Split view

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-versioned-admin#3]
While testing, when using the CMS in split view and then decreasing the screen width, the preview appears to still be enabled - even while it is not shown. 

This causes the `History` tab to not function properly. I can only see the content when loading, but then get immediately redirected to the `Content` tab.

To reproduce:

1. Open a page in the CMS
2. Select Split mode
3. Decrease the screen width
4. Click on the History tab

I am using commit 15252f3 on PHP 5.6

**Comment by robbieaverill** [comment]
Nice catch! I guess we disable the preview entirely for now

**Comment by robbieaverill** [comment]
This will be included with https://github.com/silverstripe/silverstripe-versioned/issues/99

**Comment by robbieaverill** [comment]
Fix at #6
