### ISSUE TITLE
Make use of ViewModeToggle component

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-versioned-admin#30]
https://github.com/silverstripe/silverstripe-admin/commit/5108734b19edbe9d6404b747e25059a586b009fe introduced the ViewModeToggle component that could now be injected and used to allow users to toggle between the split, preview, and edit view modes.

**Comment by robbieaverill** [comment]
Will be completed when the work for compare mode is merged in. PR at https://github.com/creative-commoners/silverstripe-versioned-admin/pull/26

**Comment by robbieaverill** [comment]
Done in #33
