### ISSUE TITLE
"Files" tab in archive admin is missing

### ISSUE THREAD

**Issue by jenniferaslan** [silverstripe/silverstripe-versioned-admin#300]
The documentation shown here describes functionality that is not showing in a SilverStripe 4.13 site I recently built and launched: 

https://github.com/silverstripe/silverstripe-userhelp-content/blob/4/docs/en/02_Creating_pages_and_content/05_Archive.md#restoring-content-to-your-website

I have added the following to my app.yml file:
 ```
SilverStripe\Assets\File:
  keep_archived_assets: true
  show_history: true
```
However, after flushing, there is no Files tab in the Archive, nor is there any Archive option on files themselves in the Files interface. Is this functionality deprecated or broken?

## Acceptance criteria
- Validate that this was not removed intentionally.
- Make sure user help in in line with the capabilities of the CMS.
- If the capability is restored, make sure it is driven by the `keep_archived_assets` flag.

## Notes
- If you don't have the `keep_archived_assets` flag set to true, this feature will be less useful because you won't have any files to restore. Maybe it got intentionally remove because of that.

## PRs
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/301
- https://github.com/silverstripe/developer-docs/pull/313
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1378
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1379

**Comment by GuySartorelli** [comment]
Thanks for reporting this. I've moved this to the versioned-admin repository, as it seems like a genuine regression.

**Comment by emteknetnz** [comment]
I've raised a [PR](https://github.com/silverstripe/silverstripe-versioned-admin/pull/301) to get the `SilverStripe\Assets\File.keep_archived_assets` config working properly as documented.

Note that `SilverStripe\AssetAdmin\Forms\FileFormFactory.show_history` is an asset-admin setting, the example in the original issue description incorrectly has this on `SilverStripe\Assets\File`

**Comment by GuySartorelli** [comment]
@emteknetnz To satisfy the acceptance criteria "Make sure user help in in line with the capabilities of the CMS." the screenshot(s) on the linked userhelp page showing an "archive" button should be updated to show a "delete" button, and the docs should explain that "delete" means "archive" if old versions of files are retained.
Alternatively, the "delete" button should be replaced with an "archive" button when `keep_archived_assets` is true.

**Comment by GuySartorelli** [comment]
This issue has now been resolved and will be automatically tagged once CI has finished running on the branch.
