### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-versioned-admin#307]
This build is breaking on the `2` branch: https://github.com/silverstripe/silverstripe-versioned-admin/actions/runs/5996379772/job/16288066883

I can confirm it is also breaking locally.

## PRs
- https://github.com/silverstripe/silverstripe-admin/pull/1562

**Comment by GuySartorelli** [comment]
This is fine with admin 2.0 but fails with admin 2 branch.
A quick git bisect on the admin repo shows https://github.com/silverstripe/silverstripe-admin/commit/a77f54b409df4af11472d37e275a9b42ce705b5f is the first bad commit.

Basically, there's something about the `useState` being added to the `Loading` component in that commit that versioned-admin _tests_ don't like.
There's no need for that ID to be held in state. The ID is just there to avoid clashes with other loading components, and doesn't need to be retained between render cycles of the component.

**Comment by sabina-talipova** [comment]
Build works https://github.com/silverstripe/silverstripe-versioned-admin/actions/runs/5996379772/job/16292234936
Issue was solved. Close.
