### ISSUE TITLE
Restoring a page crashes while redirect call

### ISSUE THREAD

**Issue by bumbus** [silverstripe/silverstripe-versioned-admin#316]
Seems to happen with SilverStripe 5 on php 8.1.

Following Error:

```
[Emergency] Uncaught TypeError: SilverStripe\Admin\LeftAndMain::redirect(): Argument #2 ($code) must be of type int, string given, called in /var/www/html/vendor/silverstripe/versioned-admin/src/Extensions/ArchiveRestoreAction.php on line 92
```

It looks like this call:
https://github.com/silverstripe/silverstripe-versioned-admin/blob/2/src/Extensions/ArchiveRestoreAction.php#L92

does not meet the type spec of this function:
https://github.com/silverstripe/silverstripe-framework/blob/5/src/Control/Controller.php#L598

I wonder why `index` should be a http status code.

**Comment by emteknetnz** [comment]
Could you please provide some replication steps

**Comment by bumbus** [comment]
@emteknetnz meanwhile it looks like the problem was fixed already
