### ISSUE TITLE
Error in ArchiveRestoreAction.php on line 92 where 2nd arg is invalid type

### ISSUE THREAD

**Issue by ssmarco** [silverstripe/silverstripe-versioned-admin#330]
### Module version(s) affected

2.1.2

### Description

When restoring an archived Elemental block, as shown in the screenshot below, an error occurs due to invalid argument passed to the 2nd parameter of `redirect` function. Instead if an `int` a `string` is passed, hence the redirection did not work to the target page.

![image](https://github.com/silverstripe/silverstripe-versioned-admin/assets/26287674/1522b5c8-20c5-400e-8608-8cfc48cb3887)

### How to reproduce

The method, `doRestore` of `ArchivedRestoreAction` class is calling `redirect` method of the controller but passing a string as the 2nd argument. This is now incorrect due to PHP 8.2 strict typing applied to CMS 5.1 hence creating an error.

Line 92: `return $controller->redirect($controller->Link(), 'index');`

### Possible Solution

The fix should be to remove the 2nd argument since `index` is default behaviour.

Line 92: `return $controller->redirect($controller->Link());`

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## Acceptance criteria
- [x] No errors are thrown when restoring a Page or Content block.
- [x] Restoration of page or content block is covered by some PHPunit test and at least some Behat test.

## PRs
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/331
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/334
- https://github.com/silverstripe/silverstripe-elemental/pull/1167

**Comment by GuySartorelli** [comment]
PR merged. This will be automatically tagged by GitHub actions

**Comment by MichAlkhouri** [comment]
Does this fix cover archiving a page?
From my testing I can see archiving a page behave the same way and produces the same error.

**Comment by maxime-rainville** [comment]
Good job on the fix ... but this looks like something our CI should have pick it up. I'll reopen to cover this functionality with some test.

**Comment by GuySartorelli** [comment]
PRs merged
