### ISSUE TITLE
BUG Alignment of table cells is slightly out when version column has one character

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-versioned-admin#35]
![image](https://user-images.githubusercontent.com/5170590/43805400-a4da08dc-9af3-11e8-8327-243a6b1a53c7.png)

**Version: master**

When the version column has one character e.g. # or 7 and some columns have two characters (e.g. 20) the other columns are pushed out of alignment.

**Comment by raissanorth** [comment]
I cannot reproduce this issue using master on either a project created with `silverstripe/installer`, or by using the `cwp/cwp-recipe-kitchen-sink`.

![image](https://user-images.githubusercontent.com/14869519/43930857-d6a5612a-9c8f-11e8-9d2b-68443a3eafe0.png)

![image](https://user-images.githubusercontent.com/14869519/43930864-dafc22f4-9c8f-11e8-8722-c9fbc571e278.png)

**Comment by robbieaverill** [comment]
Fixed in #33 - thanks @raissanorth!
