### ISSUE TITLE
BUG When one version in compare mode is selected hover and tooltip indicate "click for details"

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-versioned-admin#36]
![image](https://user-images.githubusercontent.com/5170590/43805466-f057353c-9af3-11e8-8601-b12aec3f7975.png)

**Version: master**

When you enter compare mode and select one version the hover state of the selected row indicates that it should be clickable, and the tooltip says "click to view details".

Clicking it doesn't do anything.

**Comment by robbieaverill** [comment]
We should not be rendering this row as an anchor in this situation, we can use a span instead as long as it's still tabbable.

**Comment by robbieaverill** [comment]
PR at #44

**Comment by raissanorth** [comment]
PR was merged, so I'm closing the ticket.
