### ISSUE TITLE
BUG "Already selected" indicator is missing from selected version in compare mode

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-versioned-admin#37]
![image](https://user-images.githubusercontent.com/5170590/43805514-28b88c14-9af4-11e8-989e-558e3c96d2f0.png)

**Version: master**

When a version is selected in compare mode and is anchored to the top of the list, the version _in the list_ should say "Already selected", and when hovered it should fade out and be replaced with the "X" remove button.

See designs: https://projects.invisionapp.com/share/FJEHOLLEN#/screens/263513627

**Comment by raissanorth** [comment]
Closely related to https://github.com/silverstripe/silverstripe-versioned-admin/pull/33

WIP fix: https://github.com/creative-commoners/silverstripe-versioned-admin/tree/pulls/1/add-already-selected-indicator-in-compare-mode

Depends on: https://github.com/creative-commoners/silverstripe-admin/tree/pulls/1/add-onMouseLeave-to-FormAction-component

Problems still to solve:

- Should the clear button appear only on hovering over the "Already selected" message or the entire row?
- Currently when one hovers over the message, the button appears, and disappears when hovering away from the button. If the hover is over the row however, but outside of the actions section, the mouseLeave event is not triggered and the button stays - when the message should reappear.

**Comment by robbieaverill** [comment]
Fixed with #46
