### ISSUE TITLE
Unable to restore pages from archive with ElementalArea extension applied

### ISSUE THREAD

**Issue by TheSceneman** [silverstripe/silverstripe-versioned-admin#378]
### Module version(s) affected

2.3.0

### Description

When clicking the "restore draft" button on an archived page, the webpage gets stuck on the Silverstripe CMS logo spinner. The console output is a breaking javascript error: `Cannot read properties of undefined (reading 'elemental-area-id')`

### How to reproduce

Archive a page with an elemental area.
Go to archive admin.
Open archived page.
Click restore draft.

### Possible Solution

@GuySartorelli has a fix for this

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

## PRs
- https://github.com/silverstripe/silverstripe-elemental/pull/1292

**Comment by emteknetnz** [comment]
Linked PR has been merged, a patch released will automatically tagged shortly
