### ISSUE TITLE
Reduce size of border radius on compare mode warning

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-versioned-admin#38]
The border radius I think is `$border-radius-lg` at the moment, let's switch it for `$border-radius`.

Original designs:

![image](https://user-images.githubusercontent.com/5170590/43805880-868da21a-9af5-11e8-8c92-f72783a517a3.png)

What we have now:

![image](https://user-images.githubusercontent.com/5170590/43805889-8df8b486-9af5-11e8-939d-69681019801a.png)

**Comment by robbieaverill** [comment]
Fix at #43

**Comment by raissanorth** [comment]
Fixed via #43
