### ISSUE TITLE
HistoryViewer Compare  enablable when only one version exists

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-versioned-admin#49]
This feature doesn't make sense in the context of only one version, so some additional logic will need to be implemented:

User is asked to select two versions 😉 : 

![image](https://user-images.githubusercontent.com/14869519/44373314-b8b09080-a53c-11e8-8d16-8a0cf3cb37ce.png)

**Comment by robbieaverill** [comment]
So don't allow compare mode to be enabled when there's only one version?

**Comment by raissanorth** [comment]
Thanks @robbieaverill  for translating, haha.

**Comment by robbieaverill** [comment]
PR at #50
