### ISSUE TITLE
Contribute to React HistoryViewer translations...

### ISSUE THREAD

**Issue by Martimiz** [silverstripe/silverstripe-versioned-admin#81]
Hi
I would like to contribute to the translations in the new React HistoryViewer and I guess translations should be in a json file format and then converted to .js, but I can't seem to find any reference in code nor in Transifex...

Temporary in my app I fixed it importing a nl.js file into the cms as custom css, but... :)

**Comment by Martimiz** [comment]
Btw: that is in 4.2.1 - but I don't suppose we reverted back to php in 5?

**Comment by robbieaverill** [comment]
Hi @Martimiz, yes we haven't compiled the source language file yet. I'll have a look at doing it now

**Comment by robbieaverill** [comment]
@Martimiz I've pushed the English source file for the JavaScript translations now, feel free to get going with it - thanks for raising this issue =)

https://www.transifex.com/silverstripe/silverstripe-versioned-admin/master-js/

**Comment by Martimiz** [comment]
Thanks, started it, and then someone took over the rest, so it was much awaited I guess :)
