### ISSUE TITLE
Diff doesn't show an entirely new line as an addition

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-versioned-admin#82]
**Version: SS 4.3.0-rc1** (in CWP 2.2.0-rc1 context)

* Create a page
* Add some content and publish
* Add a new paragraph to the content and publish
* Modify the paragraph and publish

Expected: when comparing the latest version against the previous version it should show the modified change as a diff
Actual: working ✅ 

Expected: when comparing the latest version against the second-previous version, it should show the added line as a diff
Actual: it doesn't - looks like the content hasn't changed at all between the versions

### Modification diff

![image](https://user-images.githubusercontent.com/5170590/48344222-14db0a80-e67d-11e8-9efb-3b33597aed93.png)

### Addition diff

![image](https://user-images.githubusercontent.com/5170590/48344237-1dcbdc00-e67d-11e8-859d-9bb0eeba2eeb.png)

In this screenshot the whole last line should be highlighted as an addition.

**Comment by chillu** [comment]
Here's an addition to `DataDifferencer.php` which demonstrates this case ... I think. 

```php
    public function testHtmlWithParagraph()
    {
        $before = new TestObject([
            'Content' => "<p>foo</p>\n<p>bar</p>"
        ]);
        $after = new TestObject([
            'Content' => "<p>inserted</p>\n<p>bar modified</p>"
        ]);
        $differ = new DataDifferencer($before, $after);
        $diff = $differ->diffedData();
        $this->assertContainsIgnoreWhitespace(
            '<p><del>foo</del></p>',
            $diff->getField('Content'),
            'Paragraph deletion'
        );
        $this->assertContainsIgnoreWhitespace(
            '<p><ins>inserted</ins></p>',
            $diff->getField('Content'),
            'Paragraph insertion'
        );
        $this->assertContainsIgnoreWhitespace(
            '<p>bar <ins>modified</ins></p>',
            $diff->getField('Content'),
            'Paragraph modification'
        );
    }
```

**Comment by GuySartorelli** [comment]
Closing this in favor of #212.
