### ISSUE TITLE
Reverting pages is a little too optimistic

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-versioned-admin#85]
### Affected Versions

All

### Description

Currently when reverting pages the previous versions you immediately get feedback although the GraphQL mutation is still running.

### Steps to Reproduce

- Open the history for a page with a bunch of versions (preferably a page with many relations that will cause a longer time to rollback)
- Choose a version in the past
- Open the developer console so you can monitor requests
- Click the option to revert to the chosen version
- Note that you immediately return to the version list with a success message but the GraphQL mutation has only fired, not returned yet.

### Notes

We might want to have some sort of UX for long rollbacks? Do we just want to have a loading indicator on the page? Do we accept that rollbacks might be a time intensive process? /cc @clarkepaul

**Comment by ScopeyNZ** [comment]
I've raised this as a high impact because in some instances I've observed (especially with the fixes applied in silverstripe/silverstripe-cms#2329) the rollback can take ~20 seconds and you really don't know what's going on - it's very confusing.

**Comment by robbieaverill** [comment]
This was by design, it's not a bug. We could add a loading indicator while the new record is waiting to be pushed into the top of the list though, that might help?

**Comment by newleeland** [comment]
Ideally we would want to show reverting progress immediately if possible, if the reverting takes more than 7s. it would be beneficial to use determinate loading indicator (i.e. shows progress/time remaining). Indeterminate loading indicators are not really effective beyond 7s, as there is no indication of how much time is remaining, content is loaded or what is left to load.

do you know what caused the revert to take 20s @ScopeyNZ?
Are we able to gradually load in content to show progression in some capacity?

**Comment by robbieaverill** [comment]
>do you know what caused the revert to take 20s

Site size really - as the site gets bigger everything gets slower

I don't think we can do determinate loading indicators, because we'd need to know the limit of how long something will take to complete. This is an example where we won't know that unfortunately

**Comment by ScopeyNZ** [comment]
Perhaps @newleeland / @clarkepaul can think of a good UI flow given these recent details?

**Comment by newleeland** [comment]
> Dev actions:
> 
> * Make the "Revert to this version" button disabled AND in a loading state (currently just disables)
> * Don't clear the current version from the redux store until the mutation has completed

I would like to add, would be good to remove the immediate success alert banner the user receives when clicking revert, as well. So it doesn't confuse people after clicking revert and while the loading indicator is spinning.

Another alternative would be to just replace the success alert with a informative alert (blue) stating that "reverting is in progress. This may take up to a minute for larger sites" and change to a success toast once everything is full reverted. 
- just to give them an expectation of how long it take, 
- Stating it their site being large is the cause 
- undercutting their expectation of a minute, when it finishes in 20s

**Comment by chillu** [comment]
Removing milestone, we're in RC stage for this, meaning we can only really slot in security issues.

**Comment by ScopeyNZ** [comment]
Closed in #91 . If there's some UX follow up that we want to do here then feel free to raise it in another issue.
