### ISSUE TITLE
Multiple "LIVE" badges when only one version can be live

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-versioned-admin#95]
As you can see from the screenshot the selected version no.17 is showing as live but actually no.19 is the one which is really live. Only one version can be live at any given time.

Sorry I can't figure out what triggers this bug as sometimes it happens and sometimes not. 
![pasted_image_28_01_19__3_40_pm](https://user-images.githubusercontent.com/555033/51812990-bc7ce600-2318-11e9-9ec3-30e220861c65.png)

**Comment by chillu** [comment]
@unclecheese Might be something worth looking at as part of the version snapshots work?

**Comment by sachajudd** [comment]
Tested and it seems to be working in the latest versions. The 'Live' badge will be getting removed in place of versioned-snapshots so closing this issue 🙂
