### ISSUE TITLE
Indication of new additions/changes not visible enough

### ISSUE THREAD

**Issue by clarkepaul** [silverstripe/silverstripe-versioned-admin#97]
When comparing the changes of content on two version the green highlight colour to show the changes is way too light. This colour must have changed based on a variable change somewhere in the system. 
<img width="339" alt="pasted_image_28_01_19__3_10_pm" src="https://user-images.githubusercontent.com/555033/51813057-3dd47880-2319-11e9-8d5d-f591c221db85.png">

The green needs improving but probably good to check the other colours while we are at it.

To reproduce, compare to different variations of a page. Screenshot is using the latest 4.3 version.

### To Fix
See new designs here: https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5d64c5d28fc2648d288c5e18

**Notes:**
New bg colours: green: #B9F1C8, red: #FFD2DA
border-radius: 1px;

**PRs**

- [ ] #146

**Comment by ScopeyNZ** [comment]
Copying @brynwhyman's comment here from #96:

> Possibly an opinionated issue, but it's difficult to see 'updated' diff colour in the History Viewer. That's the green highlighting used to reflect an update.
>
>According to the [webaim.org color contrast checker](https://webaim.org/), "WCAG 2 level AA requires a contrast ratio of at least ... 3:1 for graphics and user interface components (such as form input borders)." I've taken this to refer to text highlighting too.
>
>Using the CMS colours in the webaim.org color contrast checker tool, it fails with a ratio of 1.07:1. [Example here](https://webaim.org/resources/contrastchecker/?fcolor=F0FFF0&bcolor=F1F3F6)
>I've used background colour of `F1F3F6` and a foreground (highlight colour) of `F0FFF0`

**Comment by sachajudd** [comment]
See new designs here: https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5d64c5d28fc2648d288c5e18

**Notes:**
New bg colours: green: #B9F1C8, red: #FFD2DA
border-radius: 1px;

These colours should also be reflected in other repos such as Advanced workflow.
